# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos/dtbo/exynos7885.dtb

dtb-$(MACH_EXYNOS7904_P200_CHN) := \
	exynos/dtbo/exynos7904-wisdomwifi_chn_hk_03.dtbo

dtb-$(MACH_EXYNOS7904_P205_OPEN) := \
	exynos/dtbo/exynos7904-wisdom_sea_open_03.dtbo

dtb-$(MACH_EXYNOS7904_T510_OPEN) := \
	exynos/dtbo/exynos7904-gta3xlwifi_eur_open_03.dtbo \
	exynos/dtbo/exynos7904-gta3xlwifi_eur_open_04.dtbo

dtb-$(MACH_EXYNOS7904_T515_OPEN) := \
	exynos/dtbo/exynos7904-gta3xl_eur_open_03.dtbo \
	exynos/dtbo/exynos7904-gta3xl_eur_open_04.dtbo

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo